use std::process::Command;

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // https://stackoverflow.com/a/44407625/5936187
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .unwrap();
    let git_hash = String::from_utf8(output.stdout).unwrap();
    println!("cargo:rustc-env=GIT_HASH={git_hash}");
    println!("cargo:rustc-rerun-if-changed=.git/HEAD");
    println!("cargo:rustc-env=DATABASE_URL=sqlite:database.db");
}
