version: '3'
services:
  discord-bot:
    build: .
    volumes:
      - ./database.db:/database.db:rw
    environment:
      - DATABASE_URL=sqlite:/database.db
      - NO_PERFORM_LOAD_ENV_FILE=1
    env_file:
      - CONFIG.env